### ISSUE TITLE
Phone and Email are not found in the Excel worksheet

### ISSUE THREAD

**Issue by pooriaarab** [lyyka/google-maps-businesses-scraper#1]

**Comment by lyyka** [comment]
> Hi,
> 
> 
> 
> I get this error in the terminal which I am not sure how to overcome:
> 
> 
> 
> [40524:41272:0102/150447.072:ERROR:device_event_log_impl.cc(211)] [15:04:47.072] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
> 
> 
> 
> And when the Excel file is created I just see the name and address of the businesses in Google Maps and their phone number and email is empty. 
> 
> 
> 
> What's the problem here, you think?

I don't know about the error, seems as if it is not connected to the scraper itself as the scraper is not using any usb ports or whatsoever.

For the empty fields, it may happen that there is no phone number? Update the chromedriver to the latest version, that may fix some issues. I am using Ubuntu 20.04 for developing this app, not sure if it works well on Windows yet.

As for the email, if you choose to scrape the website, it will still get very few emails as it is not perfected yet.
